# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "arista-veos-4.23.0.1F"

  ###################################
  #                                 #
  #   +-------+         +-------+   #
  #   |       +---Et1---+       |   #
  #   |  SW1  |         |  SW2  |   #
  #   |       +---Et2---+       |   #
  #   +-------+         +-------+   #
  #                                 #
  ###################################

  config.vm.define "SW1" do |node|
    node.vm.network :private_network,
      :libvirt__iface_name => "Et1",
      :libvirt__tunnel_type => "udp",
      :libvirt__tunnel_local_ip => "127.1.1.1",
      :libvirt__tunnel_local_port => "10001",
      :libvirt__tunnel_ip => "127.1.1.2",
      :libvirt__tunnel_port => "10001",
      auto_config: false
    node.vm.network :private_network,
      :libvirt__iface_name => "Et2",
      :libvirt__tunnel_type => "udp",
      :libvirt__tunnel_local_ip => "127.1.1.3",
      :libvirt__tunnel_local_port => "10001",
      :libvirt__tunnel_ip => "127.1.1.4",
      :libvirt__tunnel_port => "10001",
      auto_config: false
  end

  config.vm.define "SW2" do |node|
    node.vm.network :private_network,
      :libvirt__iface_name => "Et1",
      :libvirt__tunnel_type => "udp",
      :libvirt__tunnel_local_ip => "127.1.1.2",
      :libvirt__tunnel_local_port => "10001",
      :libvirt__tunnel_ip => "127.1.1.1",
      :libvirt__tunnel_port => "10001",
      auto_config: false
    node.vm.network :private_network,
      :libvirt__iface_name => "Et2",
      :libvirt__tunnel_type => "udp",
      :libvirt__tunnel_local_ip => "127.1.1.4",
      :libvirt__tunnel_local_port => "10001",
      :libvirt__tunnel_ip => "127.1.1.3",
      :libvirt__tunnel_port => "10001",
      auto_config: false
  end

end
