# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Use Vagrant's default insecure key
  config.ssh.insert_key = false
  # Set shell for SSH commands
  config.ssh.shell = "bash"
  # Set timeout to 4 mins
  config.vm.boot_timeout = 240
  # Disable default host <-> guest synced folder
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # Set guest OS type to disable autodetection
  config.vm.guest = :tinycore

  config.vm.provider :libvirt do |domain|
    domain.cpus = 1
    domain.memory = 2048
    domain.disk_bus = 'ide'
    domain.disk_driver :cache => 'none'
    domain.graphics_type = 'none'
  end
end
